name: Shell Commands

on: 
   workflow_dispatch:

jobs: 
  run-shell-command: 
    runs-on: ubuntu-latest
    steps:
      - name: echo string
        run: echo "Hello World!"
      - name: multiline commands
        run: |
           node -v
           npm -v
      - name: python command
        run: |
           import platform
           print
           (platform.processor())
